/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.matrixlib.jni;

public class NativeMatrix {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NativeMatrix(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NativeMatrix obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeMatrixLibraryJNI.delete_NativeMatrix(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NativeMatrix() {
    this(NativeMatrixLibraryJNI.new_NativeMatrix(), true);
  }

  public void resize(int numRows, int numCols) {
    NativeMatrixLibraryJNI.NativeMatrix_resize(swigCPtr, this, numRows, numCols);
  }

  public boolean mult(NativeMatrix a, NativeMatrix b) {
    return NativeMatrixLibraryJNI.NativeMatrix_mult(swigCPtr, this, NativeMatrix.getCPtr(a), a, NativeMatrix.getCPtr(b), b);
  }

  public boolean multQuad(NativeMatrix a, NativeMatrix b) {
    return NativeMatrixLibraryJNI.NativeMatrix_multQuad(swigCPtr, this, NativeMatrix.getCPtr(a), a, NativeMatrix.getCPtr(b), b);
  }

  public boolean invert(NativeMatrix a) {
    return NativeMatrixLibraryJNI.NativeMatrix_invert(swigCPtr, this, NativeMatrix.getCPtr(a), a);
  }

  public boolean solve(NativeMatrix a, NativeMatrix b) {
    return NativeMatrixLibraryJNI.NativeMatrix_solve(swigCPtr, this, NativeMatrix.getCPtr(a), a, NativeMatrix.getCPtr(b), b);
  }

  public java.nio.ByteBuffer data() {  
  return NativeMatrixLibraryJNI.NativeMatrix_data(swigCPtr, this);  
}

  public int rows() {
    return NativeMatrixLibraryJNI.NativeMatrix_rows(swigCPtr, this);
  }

  public int cols() {
    return NativeMatrixLibraryJNI.NativeMatrix_cols(swigCPtr, this);
  }

}
