/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.matrixlib.jni;

public class NativeMatrixLibraryJNI {
  public final static native void NativeMatrixImpl_nan_set(long jarg1, NativeMatrixImpl jarg1_, double jarg2);
  public final static native double NativeMatrixImpl_nan_get(long jarg1, NativeMatrixImpl jarg1_);
  public final static native long new_NativeMatrixImpl(int jarg1, int jarg2);
  public final static native void NativeMatrixImpl_resize(long jarg1, NativeMatrixImpl jarg1_, int jarg2, int jarg3);
  public final static native boolean NativeMatrixImpl_set__SWIG_0(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_);
  public final static native boolean NativeMatrixImpl_add(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, long jarg3, NativeMatrixImpl jarg3_);
  public final static native boolean NativeMatrixImpl_subtract(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, long jarg3, NativeMatrixImpl jarg3_);
  public final static native boolean NativeMatrixImpl_mult__SWIG_0(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, long jarg3, NativeMatrixImpl jarg3_);
  public final static native boolean NativeMatrixImpl_mult__SWIG_1(long jarg1, NativeMatrixImpl jarg1_, double jarg2, long jarg3, NativeMatrixImpl jarg3_, long jarg4, NativeMatrixImpl jarg4_);
  public final static native boolean NativeMatrixImpl_multAdd(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, long jarg3, NativeMatrixImpl jarg3_);
  public final static native boolean NativeMatrixImpl_multTransA(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, long jarg3, NativeMatrixImpl jarg3_);
  public final static native boolean NativeMatrixImpl_multAddTransA(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, long jarg3, NativeMatrixImpl jarg3_);
  public final static native boolean NativeMatrixImpl_multTransB(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, long jarg3, NativeMatrixImpl jarg3_);
  public final static native boolean NativeMatrixImpl_multAddTransB(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, long jarg3, NativeMatrixImpl jarg3_);
  public final static native boolean NativeMatrixImpl_addBlock(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, int jarg8, double jarg9);
  public final static native boolean NativeMatrixImpl_multAddBlock(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, long jarg3, NativeMatrixImpl jarg3_, int jarg4, int jarg5);
  public final static native boolean NativeMatrixImpl_multQuad(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, long jarg3, NativeMatrixImpl jarg3_);
  public final static native boolean NativeMatrixImpl_invert(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_);
  public final static native boolean NativeMatrixImpl_solve(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, long jarg3, NativeMatrixImpl jarg3_);
  public final static native boolean NativeMatrixImpl_solveCheck(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, long jarg3, NativeMatrixImpl jarg3_);
  public final static native boolean NativeMatrixImpl_insert__SWIG_0(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, int jarg8);
  public final static native boolean NativeMatrixImpl_insert__SWIG_1(long jarg1, NativeMatrixImpl jarg1_, double[] jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, int jarg8, int jarg9, int jarg10);
  public final static native boolean NativeMatrixImpl_extract(long jarg1, NativeMatrixImpl jarg1_, int jarg2, int jarg3, int jarg4, int jarg5, double[] jarg6, int jarg7, int jarg8, int jarg9, int jarg10);
  public final static native boolean NativeMatrixImpl_transpose(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_);
  public final static native boolean NativeMatrixImpl_removeRow(long jarg1, NativeMatrixImpl jarg1_, int jarg2);
  public final static native boolean NativeMatrixImpl_removeColumn(long jarg1, NativeMatrixImpl jarg1_, int jarg2);
  public final static native void NativeMatrixImpl_zero(long jarg1, NativeMatrixImpl jarg1_);
  public final static native boolean NativeMatrixImpl_containsNaN(long jarg1, NativeMatrixImpl jarg1_);
  public final static native boolean NativeMatrixImpl_scale__SWIG_0(long jarg1, NativeMatrixImpl jarg1_, double jarg2, long jarg3, NativeMatrixImpl jarg3_);
  public final static native boolean NativeMatrixImpl_isAprrox(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, double jarg3);
  public final static native boolean NativeMatrixImpl_set__SWIG_1(long jarg1, NativeMatrixImpl jarg1_, double[] jarg2, int jarg3, int jarg4);
  public final static native boolean NativeMatrixImpl_get__SWIG_0(long jarg1, NativeMatrixImpl jarg1_, double[] jarg2, int jarg3, int jarg4);
  public final static native double NativeMatrixImpl_min(long jarg1, NativeMatrixImpl jarg1_);
  public final static native double NativeMatrixImpl_max(long jarg1, NativeMatrixImpl jarg1_);
  public final static native double NativeMatrixImpl_sum(long jarg1, NativeMatrixImpl jarg1_);
  public final static native double NativeMatrixImpl_prod(long jarg1, NativeMatrixImpl jarg1_);
  public final static native void NativeMatrixImpl_scale__SWIG_1(long jarg1, NativeMatrixImpl jarg1_, double jarg2);
  public final static native boolean NativeMatrixImpl_set__SWIG_2(long jarg1, NativeMatrixImpl jarg1_, int jarg2, int jarg3, double jarg4);
  public final static native double NativeMatrixImpl_get__SWIG_1(long jarg1, NativeMatrixImpl jarg1_, int jarg2, int jarg3);
  public final static native int NativeMatrixImpl_rows(long jarg1, NativeMatrixImpl jarg1_);
  public final static native int NativeMatrixImpl_cols(long jarg1, NativeMatrixImpl jarg1_);
  public final static native int NativeMatrixImpl_size(long jarg1, NativeMatrixImpl jarg1_);
  public final static native void NativeMatrixImpl_print(long jarg1, NativeMatrixImpl jarg1_);
  public final static native void delete_NativeMatrixImpl(long jarg1);
  public final static native void NativeSparseMatrixImpl_nan_set(long jarg1, NativeSparseMatrixImpl jarg1_, double jarg2);
  public final static native double NativeSparseMatrixImpl_nan_get(long jarg1, NativeSparseMatrixImpl jarg1_);
  public final static native long new_NativeSparseMatrixImpl(int jarg1, int jarg2);
  public final static native void NativeSparseMatrixImpl_resize(long jarg1, NativeSparseMatrixImpl jarg1_, int jarg2, int jarg3);
  public final static native boolean NativeSparseMatrixImpl_set__SWIG_0(long jarg1, NativeSparseMatrixImpl jarg1_, long jarg2, NativeSparseMatrixImpl jarg2_);
  public final static native boolean NativeSparseMatrixImpl_add(long jarg1, NativeSparseMatrixImpl jarg1_, long jarg2, NativeSparseMatrixImpl jarg2_, long jarg3, NativeSparseMatrixImpl jarg3_);
  public final static native boolean NativeSparseMatrixImpl_subtract(long jarg1, NativeSparseMatrixImpl jarg1_, long jarg2, NativeSparseMatrixImpl jarg2_, long jarg3, NativeSparseMatrixImpl jarg3_);
  public final static native boolean NativeSparseMatrixImpl_mult__SWIG_0(long jarg1, NativeSparseMatrixImpl jarg1_, long jarg2, NativeSparseMatrixImpl jarg2_, long jarg3, NativeSparseMatrixImpl jarg3_);
  public final static native boolean NativeSparseMatrixImpl_mult__SWIG_1(long jarg1, NativeSparseMatrixImpl jarg1_, double jarg2, long jarg3, NativeSparseMatrixImpl jarg3_, long jarg4, NativeSparseMatrixImpl jarg4_);
  public final static native boolean NativeSparseMatrixImpl_multAdd(long jarg1, NativeSparseMatrixImpl jarg1_, long jarg2, NativeSparseMatrixImpl jarg2_, long jarg3, NativeSparseMatrixImpl jarg3_);
  public final static native boolean NativeSparseMatrixImpl_multTransA(long jarg1, NativeSparseMatrixImpl jarg1_, long jarg2, NativeSparseMatrixImpl jarg2_, long jarg3, NativeSparseMatrixImpl jarg3_);
  public final static native boolean NativeSparseMatrixImpl_multAddTransA(long jarg1, NativeSparseMatrixImpl jarg1_, long jarg2, NativeSparseMatrixImpl jarg2_, long jarg3, NativeSparseMatrixImpl jarg3_);
  public final static native boolean NativeSparseMatrixImpl_multTransB(long jarg1, NativeSparseMatrixImpl jarg1_, long jarg2, NativeSparseMatrixImpl jarg2_, long jarg3, NativeSparseMatrixImpl jarg3_);
  public final static native boolean NativeSparseMatrixImpl_multAddTransB(long jarg1, NativeSparseMatrixImpl jarg1_, long jarg2, NativeSparseMatrixImpl jarg2_, long jarg3, NativeSparseMatrixImpl jarg3_);
  public final static native boolean NativeSparseMatrixImpl_addBlock(long jarg1, NativeSparseMatrixImpl jarg1_, long jarg2, NativeSparseMatrixImpl jarg2_, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, int jarg8, double jarg9);
  public final static native boolean NativeSparseMatrixImpl_multAddBlock(long jarg1, NativeSparseMatrixImpl jarg1_, long jarg2, NativeSparseMatrixImpl jarg2_, long jarg3, NativeSparseMatrixImpl jarg3_, int jarg4, int jarg5);
  public final static native boolean NativeSparseMatrixImpl_multQuad(long jarg1, NativeSparseMatrixImpl jarg1_, long jarg2, NativeSparseMatrixImpl jarg2_, long jarg3, NativeSparseMatrixImpl jarg3_);
  public final static native boolean NativeSparseMatrixImpl_invert(long jarg1, NativeSparseMatrixImpl jarg1_, long jarg2, NativeSparseMatrixImpl jarg2_);
  public final static native boolean NativeSparseMatrixImpl_solve(long jarg1, NativeSparseMatrixImpl jarg1_, long jarg2, NativeSparseMatrixImpl jarg2_, long jarg3, NativeSparseMatrixImpl jarg3_);
  public final static native boolean NativeSparseMatrixImpl_solveCheck(long jarg1, NativeSparseMatrixImpl jarg1_, long jarg2, NativeSparseMatrixImpl jarg2_, long jarg3, NativeSparseMatrixImpl jarg3_);
  public final static native boolean NativeSparseMatrixImpl_insert__SWIG_0(long jarg1, NativeSparseMatrixImpl jarg1_, long jarg2, NativeSparseMatrixImpl jarg2_, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, int jarg8);
  public final static native boolean NativeSparseMatrixImpl_insert__SWIG_1(long jarg1, NativeSparseMatrixImpl jarg1_, int[] jarg2, int[] jarg3, double[] jarg4, int jarg5, int jarg6, int jarg7, int jarg8, int jarg9, int jarg10, int jarg11, int jarg12, int jarg13);
  public final static native boolean NativeSparseMatrixImpl_extract(long jarg1, NativeSparseMatrixImpl jarg1_, int jarg2, int jarg3, int jarg4, int jarg5, int[] jarg6, int[] jarg7, double[] jarg8, int[] jarg9, int jarg10, int jarg11, int jarg12, int jarg13);
  public final static native boolean NativeSparseMatrixImpl_transpose(long jarg1, NativeSparseMatrixImpl jarg1_, long jarg2, NativeSparseMatrixImpl jarg2_);
  public final static native boolean NativeSparseMatrixImpl_removeRow(long jarg1, NativeSparseMatrixImpl jarg1_, int jarg2);
  public final static native boolean NativeSparseMatrixImpl_removeColumn(long jarg1, NativeSparseMatrixImpl jarg1_, int jarg2);
  public final static native void NativeSparseMatrixImpl_zero(long jarg1, NativeSparseMatrixImpl jarg1_);
  public final static native boolean NativeSparseMatrixImpl_containsNaN(long jarg1, NativeSparseMatrixImpl jarg1_);
  public final static native boolean NativeSparseMatrixImpl_scale__SWIG_0(long jarg1, NativeSparseMatrixImpl jarg1_, double jarg2, long jarg3, NativeSparseMatrixImpl jarg3_);
  public final static native boolean NativeSparseMatrixImpl_isAprrox(long jarg1, NativeSparseMatrixImpl jarg1_, long jarg2, NativeSparseMatrixImpl jarg2_, double jarg3);
  public final static native boolean NativeSparseMatrixImpl_set__SWIG_1(long jarg1, NativeSparseMatrixImpl jarg1_, double[] jarg2, int[] jarg3, int[] jarg4, int jarg5, int jarg6, int jarg7);
  public final static native boolean NativeSparseMatrixImpl_get__SWIG_0(long jarg1, NativeSparseMatrixImpl jarg1_, double[] jarg2, int[] jarg3, int[] jarg4, int jarg5, int jarg6, int[] jarg7);
  public final static native double NativeSparseMatrixImpl_sum(long jarg1, NativeSparseMatrixImpl jarg1_);
  public final static native void NativeSparseMatrixImpl_scale__SWIG_1(long jarg1, NativeSparseMatrixImpl jarg1_, double jarg2);
  public final static native boolean NativeSparseMatrixImpl_set__SWIG_2(long jarg1, NativeSparseMatrixImpl jarg1_, int jarg2, int jarg3, double jarg4);
  public final static native double NativeSparseMatrixImpl_get__SWIG_1(long jarg1, NativeSparseMatrixImpl jarg1_, int jarg2, int jarg3);
  public final static native int NativeSparseMatrixImpl_rows(long jarg1, NativeSparseMatrixImpl jarg1_);
  public final static native int NativeSparseMatrixImpl_cols(long jarg1, NativeSparseMatrixImpl jarg1_);
  public final static native int NativeSparseMatrixImpl_size(long jarg1, NativeSparseMatrixImpl jarg1_);
  public final static native void NativeSparseMatrixImpl_print(long jarg1, NativeSparseMatrixImpl jarg1_);
  public final static native void delete_NativeSparseMatrixImpl(long jarg1);
  public final static native long new_NativeNullspaceProjectorImpl(int jarg1);
  public final static native boolean NativeNullspaceProjectorImpl_projectOnNullSpace(long jarg1, NativeNullspaceProjectorImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, long jarg3, NativeMatrixImpl jarg3_, long jarg4, NativeMatrixImpl jarg4_, double jarg5);
  public final static native void delete_NativeNullspaceProjectorImpl(long jarg1);
}
