/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.matrixlib.jni;

public class NativeMatrixImpl {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NativeMatrixImpl(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NativeMatrixImpl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeMatrixLibraryJNI.delete_NativeMatrixImpl(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NativeMatrixImpl(int numRows, int numCols) {
    this(NativeMatrixLibraryJNI.new_NativeMatrixImpl(numRows, numCols), true);
  }

  public void resize(int numRows, int numCols) {
    NativeMatrixLibraryJNI.NativeMatrixImpl_resize(swigCPtr, this, numRows, numCols);
  }

  public boolean mult(NativeMatrixImpl a, NativeMatrixImpl b) {
    return NativeMatrixLibraryJNI.NativeMatrixImpl_mult(swigCPtr, this, NativeMatrixImpl.getCPtr(a), a, NativeMatrixImpl.getCPtr(b), b);
  }

  public boolean multQuad(NativeMatrixImpl a, NativeMatrixImpl b) {
    return NativeMatrixLibraryJNI.NativeMatrixImpl_multQuad(swigCPtr, this, NativeMatrixImpl.getCPtr(a), a, NativeMatrixImpl.getCPtr(b), b);
  }

  public boolean invert(NativeMatrixImpl a) {
    return NativeMatrixLibraryJNI.NativeMatrixImpl_invert(swigCPtr, this, NativeMatrixImpl.getCPtr(a), a);
  }

  public boolean solve(NativeMatrixImpl a, NativeMatrixImpl b) {
    return NativeMatrixLibraryJNI.NativeMatrixImpl_solve(swigCPtr, this, NativeMatrixImpl.getCPtr(a), a, NativeMatrixImpl.getCPtr(b), b);
  }

  public java.nio.ByteBuffer data() {
    return NativeMatrixLibraryJNI.NativeMatrixImpl_data(swigCPtr, this);
}

  public int rows() {
    return NativeMatrixLibraryJNI.NativeMatrixImpl_rows(swigCPtr, this);
  }

  public int cols() {
    return NativeMatrixLibraryJNI.NativeMatrixImpl_cols(swigCPtr, this);
  }

  public int size() {
    return NativeMatrixLibraryJNI.NativeMatrixImpl_size(swigCPtr, this);
  }

  public void print() {
    NativeMatrixLibraryJNI.NativeMatrixImpl_print(swigCPtr, this);
  }

}
