/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.matrixlib.jni;

public class NativeSparseMatrixImpl {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NativeSparseMatrixImpl(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NativeSparseMatrixImpl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeMatrixLibraryJNI.delete_NativeSparseMatrixImpl(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNan(double value) {
    NativeMatrixLibraryJNI.NativeSparseMatrixImpl_nan_set(swigCPtr, this, value);
  }

  public double getNan() {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_nan_get(swigCPtr, this);
  }

  public NativeSparseMatrixImpl(int numRows, int numCols) {
    this(NativeMatrixLibraryJNI.new_NativeSparseMatrixImpl(numRows, numCols), true);
  }

  public void resize(int numRows, int numCols) {
    NativeMatrixLibraryJNI.NativeSparseMatrixImpl_resize(swigCPtr, this, numRows, numCols);
  }

  public boolean set(NativeSparseMatrixImpl a) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_set__SWIG_0(swigCPtr, this, NativeSparseMatrixImpl.getCPtr(a), a);
  }

  public boolean add(NativeSparseMatrixImpl a, NativeSparseMatrixImpl b) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_add(swigCPtr, this, NativeSparseMatrixImpl.getCPtr(a), a, NativeSparseMatrixImpl.getCPtr(b), b);
  }

  public boolean subtract(NativeSparseMatrixImpl a, NativeSparseMatrixImpl b) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_subtract(swigCPtr, this, NativeSparseMatrixImpl.getCPtr(a), a, NativeSparseMatrixImpl.getCPtr(b), b);
  }

  public boolean mult(NativeSparseMatrixImpl a, NativeSparseMatrixImpl b) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_mult__SWIG_0(swigCPtr, this, NativeSparseMatrixImpl.getCPtr(a), a, NativeSparseMatrixImpl.getCPtr(b), b);
  }

  public boolean mult(double scale, NativeSparseMatrixImpl a, NativeSparseMatrixImpl b) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_mult__SWIG_1(swigCPtr, this, scale, NativeSparseMatrixImpl.getCPtr(a), a, NativeSparseMatrixImpl.getCPtr(b), b);
  }

  public boolean multAdd(NativeSparseMatrixImpl a, NativeSparseMatrixImpl b) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_multAdd(swigCPtr, this, NativeSparseMatrixImpl.getCPtr(a), a, NativeSparseMatrixImpl.getCPtr(b), b);
  }

  public boolean multTransA(NativeSparseMatrixImpl a, NativeSparseMatrixImpl b) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_multTransA(swigCPtr, this, NativeSparseMatrixImpl.getCPtr(a), a, NativeSparseMatrixImpl.getCPtr(b), b);
  }

  public boolean multAddTransA(NativeSparseMatrixImpl a, NativeSparseMatrixImpl b) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_multAddTransA(swigCPtr, this, NativeSparseMatrixImpl.getCPtr(a), a, NativeSparseMatrixImpl.getCPtr(b), b);
  }

  public boolean multTransB(NativeSparseMatrixImpl a, NativeSparseMatrixImpl b) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_multTransB(swigCPtr, this, NativeSparseMatrixImpl.getCPtr(a), a, NativeSparseMatrixImpl.getCPtr(b), b);
  }

  public boolean multAddTransB(NativeSparseMatrixImpl a, NativeSparseMatrixImpl b) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_multAddTransB(swigCPtr, this, NativeSparseMatrixImpl.getCPtr(a), a, NativeSparseMatrixImpl.getCPtr(b), b);
  }

  public boolean addBlock(NativeSparseMatrixImpl a, int destStartRow, int destStartColumn, int srcStartRow, int srcStartColumn, int numberOfRows, int numberOfColumns, double scale) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_addBlock(swigCPtr, this, NativeSparseMatrixImpl.getCPtr(a), a, destStartRow, destStartColumn, srcStartRow, srcStartColumn, numberOfRows, numberOfColumns, scale);
  }

  public boolean multAddBlock(NativeSparseMatrixImpl a, NativeSparseMatrixImpl b, int rowStart, int colStart) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_multAddBlock(swigCPtr, this, NativeSparseMatrixImpl.getCPtr(a), a, NativeSparseMatrixImpl.getCPtr(b), b, rowStart, colStart);
  }

  public boolean multQuad(NativeSparseMatrixImpl a, NativeSparseMatrixImpl b) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_multQuad(swigCPtr, this, NativeSparseMatrixImpl.getCPtr(a), a, NativeSparseMatrixImpl.getCPtr(b), b);
  }

  public boolean invert(NativeSparseMatrixImpl a) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_invert(swigCPtr, this, NativeSparseMatrixImpl.getCPtr(a), a);
  }

  public boolean solve(NativeSparseMatrixImpl a, NativeSparseMatrixImpl b) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_solve(swigCPtr, this, NativeSparseMatrixImpl.getCPtr(a), a, NativeSparseMatrixImpl.getCPtr(b), b);
  }

  public boolean solveCheck(NativeSparseMatrixImpl a, NativeSparseMatrixImpl b) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_solveCheck(swigCPtr, this, NativeSparseMatrixImpl.getCPtr(a), a, NativeSparseMatrixImpl.getCPtr(b), b);
  }

  public boolean insert(NativeSparseMatrixImpl src, int srcY0, int srcY1, int srcX0, int srcX1, int dstY0, int dstX0) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_insert__SWIG_0(swigCPtr, this, NativeSparseMatrixImpl.getCPtr(src), src, srcY0, srcY1, srcX0, srcX1, dstY0, dstX0);
  }

  public boolean insert(int[] srcColIdexPtr, int[] srcNzRowPtr, double[] srcValuePtr, int srcRows, int srcCols, int srcNnz, int srcY0, int srcY1, int srcX0, int srcX1, int dstY0, int dstX0) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_insert__SWIG_1(swigCPtr, this, srcColIdexPtr, srcNzRowPtr, srcValuePtr, srcRows, srcCols, srcNnz, srcY0, srcY1, srcX0, srcX1, dstY0, dstX0);
  }

  public boolean extract(int srcY0, int srcY1, int srcX0, int srcX1, int[] dstColIndexPtr, int[] dstNzRowPtr, double[] dstValuePtr, int[] dstNnz, int dstRows, int dstCols, int dstY0, int dstX0) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_extract(swigCPtr, this, srcY0, srcY1, srcX0, srcX1, dstColIndexPtr, dstNzRowPtr, dstValuePtr, dstNnz, dstRows, dstCols, dstY0, dstX0);
  }

  public boolean transpose(NativeSparseMatrixImpl a) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_transpose(swigCPtr, this, NativeSparseMatrixImpl.getCPtr(a), a);
  }

  public void zero() {
    NativeMatrixLibraryJNI.NativeSparseMatrixImpl_zero(swigCPtr, this);
  }

  public boolean containsNaN() {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_containsNaN(swigCPtr, this);
  }

  public boolean scale(double scale, NativeSparseMatrixImpl src) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_scale__SWIG_0(swigCPtr, this, scale, NativeSparseMatrixImpl.getCPtr(src), src);
  }

  public boolean isAprrox(NativeSparseMatrixImpl other, double precision) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_isAprrox(swigCPtr, this, NativeSparseMatrixImpl.getCPtr(other), other, precision);
  }

  public boolean set(double[] data, int[] nz_rows, int[] col_idx, int rows, int cols, int nnz) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_set__SWIG_1(swigCPtr, this, data, nz_rows, col_idx, rows, cols, nnz);
  }

  public boolean get(double[] data, int[] nz_rows, int[] col_idx, int rows, int cols, int[] nnz) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_get__SWIG_0(swigCPtr, this, data, nz_rows, col_idx, rows, cols, nnz);
  }

  public double sum() {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_sum(swigCPtr, this);
  }

  public void scale(double scale) {
    NativeMatrixLibraryJNI.NativeSparseMatrixImpl_scale__SWIG_1(swigCPtr, this, scale);
  }

  public boolean set(int row, int col, double value) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_set__SWIG_2(swigCPtr, this, row, col, value);
  }

  public double get(int row, int col) {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_get__SWIG_1(swigCPtr, this, row, col);
  }

  public int rows() {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_rows(swigCPtr, this);
  }

  public int cols() {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_cols(swigCPtr, this);
  }

  public int size() {
    return NativeMatrixLibraryJNI.NativeSparseMatrixImpl_size(swigCPtr, this);
  }

  public void print() {
    NativeMatrixLibraryJNI.NativeSparseMatrixImpl_print(swigCPtr, this);
  }

}
