/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.matrixlib.jni;

public class NativeMatrixLibraryJNI {
  public final static native long new_NativeMatrix();
  public final static native void NativeMatrix_resize(long jarg1, NativeMatrix jarg1_, int jarg2, int jarg3);
  public final static native boolean NativeMatrix_mult(long jarg1, NativeMatrix jarg1_, long jarg2, NativeMatrix jarg2_, long jarg3, NativeMatrix jarg3_);
  public final static native boolean NativeMatrix_multQuad(long jarg1, NativeMatrix jarg1_, long jarg2, NativeMatrix jarg2_, long jarg3, NativeMatrix jarg3_);
  public final static native boolean NativeMatrix_invert(long jarg1, NativeMatrix jarg1_, long jarg2, NativeMatrix jarg2_);
  public final static native boolean NativeMatrix_solve(long jarg1, NativeMatrix jarg1_, long jarg2, NativeMatrix jarg2_, long jarg3, NativeMatrix jarg3_);
  public final static native java.nio.ByteBuffer NativeMatrix_data(long jarg1, NativeMatrix jarg1_);
  public final static native int NativeMatrix_rows(long jarg1, NativeMatrix jarg1_);
  public final static native int NativeMatrix_cols(long jarg1, NativeMatrix jarg1_);
  public final static native void delete_NativeMatrix(long jarg1);
}
