/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.matrixlib.jni;

public class NativeMatrixLibraryJNI {
  public final static native long new_NativeMatrixImpl(int jarg1, int jarg2);
  public final static native void NativeMatrixImpl_resize(long jarg1, NativeMatrixImpl jarg1_, int jarg2, int jarg3);
  public final static native boolean NativeMatrixImpl_mult(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, long jarg3, NativeMatrixImpl jarg3_);
  public final static native boolean NativeMatrixImpl_multQuad(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, long jarg3, NativeMatrixImpl jarg3_);
  public final static native boolean NativeMatrixImpl_invert(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_);
  public final static native boolean NativeMatrixImpl_solve(long jarg1, NativeMatrixImpl jarg1_, long jarg2, NativeMatrixImpl jarg2_, long jarg3, NativeMatrixImpl jarg3_);
  public final static native java.nio.ByteBuffer NativeMatrixImpl_data(long jarg1, NativeMatrixImpl jarg1_);
  public final static native int NativeMatrixImpl_rows(long jarg1, NativeMatrixImpl jarg1_);
  public final static native int NativeMatrixImpl_cols(long jarg1, NativeMatrixImpl jarg1_);
  public final static native int NativeMatrixImpl_size(long jarg1, NativeMatrixImpl jarg1_);
  public final static native void NativeMatrixImpl_print(long jarg1, NativeMatrixImpl jarg1_);
  public final static native void delete_NativeMatrixImpl(long jarg1);
}
