/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package us.ihmc.matrixlib.jni;

public class NativeNullspaceProjectorImpl {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected NativeNullspaceProjectorImpl(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NativeNullspaceProjectorImpl obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NativeMatrixLibraryJNI.delete_NativeNullspaceProjectorImpl(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NativeNullspaceProjectorImpl(int degreesOfFreedom) {
    this(NativeMatrixLibraryJNI.new_NativeNullspaceProjectorImpl(degreesOfFreedom), true);
  }

  public boolean projectOnNullSpace(NativeMatrixImpl A, NativeMatrixImpl B, NativeMatrixImpl x, double alpha) {
    return NativeMatrixLibraryJNI.NativeNullspaceProjectorImpl_projectOnNullSpace(swigCPtr, this, NativeMatrixImpl.getCPtr(A), A, NativeMatrixImpl.getCPtr(B), B, NativeMatrixImpl.getCPtr(x), x, alpha);
  }

}
