name: Run Gradle test

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  gradle-test:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/gradle-test.yml@main
  test-linux:
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.14.3"
      - name: Check Java/Gradle versions
        run: |
          java --version
          gradle --version
      - name: Run tests
        run: |
          gradle test
  test-windows:
    runs-on: [windows-2022]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.14.3"
      - name: Check Java/Gradle versions
        run: |
          java --version
          gradle --version
      - name: Run tests
        run: |
          gradle test
  test-macos-intel:
    runs-on: [macos-13] # macos-13 is exclusively x86_64 intel
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.14.3"
      - name: Check Java/Gradle versions
        run: |
          java --version
          gradle --version
      - name: Run tests
        run: |
          gradle test
  test-macos-arm:
    runs-on: [macos-14] # macos-14 runner is exclusively arm64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.14.3"
      - name: Check Java/Gradle versions
        run: |
          java --version
          gradle --version
      - name: Run tests
        run: |
          gradle test
